# Generated by Django 4.2.8 on 2023-12-28 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=128, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='OtherImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='models/other_images/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Другое фото',
                'verbose_name_plural': 'Другие фото',
            },
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa', models.CharField(max_length=256, verbose_name='Виза')),
            ],
            options={
                'verbose_name': 'Виза',
                'verbose_name_plural': 'Виза',
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='ФИО')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('bSize', models.IntegerField()),
                ('interPassport', models.BooleanField(verbose_name='Загран паспорт')),
                ('mainImage', models.ImageField(upload_to='models/main_images/', verbose_name='Главное фото')),
                ('languages', models.ManyToManyField(to='models.languages', verbose_name='Языки')),
                ('otherImages', models.ManyToManyField(to='models.otherimages', verbose_name='Другие фото')),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.visa', verbose_name='Виза')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
    ]
