# Generated by Django 4.2.8 on 2023-12-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='visa',
        ),
        migrations.AddField(
            model_name='models',
            name='visa',
            field=models.ManyToManyField(to='models.visa', verbose_name='Виза'),
        ),
    ]
