# Generated by Django 4.2.8 on 2023-12-28 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0002_remove_models_visa_models_visa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('content', models.TextField(verbose_name='Контент')),
                ('model_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.models', verbose_name='ID моделя')),
            ],
            options={
                'verbose_name': 'Запрос клиента',
                'verbose_name_plural': 'Запросы клиентов',
            },
        ),
    ]
